apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: my-postgres
        image: postgres:10.4
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: myconfigmap
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pvc
# psql -h 172.16.10.101 -U postgresadmin --password -p 30080 postgresdb
